### ISSUE TITLE
你好，请问这个扩展是不是不支持2.0？

### ISSUE THREAD

**Issue by ygcool** [changzhong/extension-google-authenticator#1]
你好，请问这个扩展是不是不支持2.0？

**Comment by Polarisjiumengyichang** [comment]
1.*  安装成功了怎么没效果 也启用了

**Comment by changzhong** [comment]
> 

是的，没有测试过2.0版本

**Comment by imnpc** [comment]
不支持V2  需要修改代码

**Comment by JianJiaPHP** [comment]
不支持2.0
再问一下有2.0的其他的包吗

**Comment by asundust** [comment]
@ygcool @changzhong @imnpc @JianJiaPHP  支持V2版本

https://github.com/asundust/dcat-auth-google-2fa
